### ISSUE TITLE
Consider using SkinMustache

### ISSUE THREAD

**Issue by jdlrobson** [Wikimedia-AU/MediaWiki-skin#15]
I saw you are working on this during inspiration week. I'm curious if you've taken a look at SkinMustache as a simpler way to build your skin. I'd be super interested in supporting you using it and uncovering bugs/problems as I've been trying to move us away from BaseTemplate in our codebases :).

Lemme know!

**Comment by samwilson** [comment]
I must admit I've been only vaguely aware of SkinMustache, sorry! I looked at it a while ago and got discouraged that it wasn't Twig. :-P

I'll have a dig and see about switching this skin to it. Doesn't sound like it'd be too hard. I assume I'd subclass `SkinMustache` in order to add my own functions etc.? The Example skin doesn't have anything like that. For example, this [weird title-building thing](https://github.com/Wikimedia-AU/MediaWiki-skin/blob/bc0e5d4e3b78828d2d6f2174c8d4cc2abfe2a994/includes/WMAUTemplate.php#L25-L33) (I'm so over having everything smashed up against the namespace colon).

**Comment by jdlrobson** [comment]
I could submit a few patches to get you started. I think you will like the data/template separation even if it's not Twig :)

**Comment by samwilson** [comment]
I've had a pretty crap go at it in #16. There's a bunch of stuff I'm not sure about, and am hacking lots. But I'm learning! :-)

Is [this talk page](https://www.mediawiki.org/wiki/Manual_talk:How_to_make_a_MediaWiki_skin) the best place to ask questions of you?

**Comment by jdlrobson** [comment]
Yeh! Or here! I'll happily use this as an excuse to improve the docs!

**Comment by jdlrobson** [comment]
Looks like this can be closed now :)
